name: FreeRegion
main: lihad.FreeRegion.FreeRegion
version: 1.5
commands:
  freeregion:
    description: Invalid Command
    usage: Invalid Command
  fr:
    description: Invalid Command
    usage: Invalid Command